### ISSUE TITLE
`typeOf` complaining 'Ambiguous type variable'

### ISSUE THREAD

**Issue by KiaraGrouwstra** [haskell-hint/hint#102]
Apparently, types of expressions containing unresolved type variables are handled okay by GHCI, yet not by Hint:

GHCI:
> > :t show undefined
> show undefined :: String

Hint:
> import Language.Haskell.Interpreter
> runInterpreter $ do; setImportsF [ ModuleImport "Prelude" NotQualified NoImportList ] >>= const (eval "show undefined")

> Left (WontCompile [GhcError {errMsg = "<interactive>:3:1: error:\n    \8226 Ambiguous type variable \8216a0\8217 arising from a use of \8216show\8217\n      prevents the constraint \8216(Show a0)\8217 from being solved.\n      Probable fix: use a type annotation to specify what \8216a0\8217 should be.\n      These potential instances exist:\n        instance Show Ordering -- Defined in \8216GHC.Show\8217\n        instance Show Integer -- Defined in \8216GHC.Show\8217\n        instance Show a => Show (Maybe a) -- Defined in \8216GHC.Show\8217\n        ...plus 22 others\n        ...plus 12 instances involving out-of-scope types\n        (use -fprint-potential-instances to see them all)\n    \8226 In the expression: show undefined\n      In an equation for \8216e_1\8217: e_1 = show undefined\n      In the first argument of \8216show_M1940135555551080679417702\8217, namely\n        \8216(let e_1 = show undefined in e_1)\8217"}])

**Comment by gelisam** [comment]
Hmm, maybe this has to do with type defaulting? I can reproduce the problem in ghci if I disable type defaulting:

```
$ ghci
λ> default ()
λ> :t show undefined
Ambiguous type variable ‘a0’ arising from a use of ‘show’
[...]
```

Interestingly, I get a different result with `show 42`, which should also be ambiguous since `42`'s type isn't `Int`, it's `Num a => a`. `typeOf "show 42"` yields `"String"`, whereas in ghci with type-defaulting disabled, `:t show 42` complains about the ambiguous type variable.

**Comment by gelisam** [comment]
A careful reading of the Haskell Report clarifies that [type defaulting should _only_ occur when the ambiguous type has a Num constraint](https://www.haskell.org/onlinereport/decls.html#:~:text=at%20least%20one%20of%20these%20classes%20is%20a%20numeric%20class). So it looks like hint is standard-compliant while ghci is not; but that makes no sense since they are both implemented using the ghci library.

**Comment by gelisam** [comment]
Aha! ghc extends the report's type-defaulting rules, but [only in ghci or if the Extended Default Rules flag is given](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html?highlight=extended%20default%20rules#extension-NoExtendedDefaultRules:~:text=At%20the%20GHCi%20prompt%2C%20or%20with%20GHC%20if%20the%20ExtendedDefaultRules%20flag%20is%20given). Therefore, if you want the same behaviour in hint, you need to pass the Extended Default Rules flag explicitly:

```haskell
import qualified Language.Haskell.Interpreter as Hint
import qualified Language.Haskell.Interpreter.Unsafe as Hint

test :: IO (Either Hint.InterpreterError String)
test = Hint.unsafeRunInterpreterWithArgs ["-fextended-default-rules"] $ do
  Hint.setImports ["Prelude"]
  Hint.typeOf "show undefined"
```
