### ISSUE TITLE
Example from ReadMe is not working

### ISSUE THREAD

**Issue by yaitskov** [haskell-hint/hint#119]
There are several bugs. runInterpreter is used without Hint prefix and fixing this issue I get infinite type error:

```
    • Occurs check: cannot construct the infinite type:
        t ~ Either Hint.InterpreterError t
      Expected type: IO t
        Actual type: IO (Either Hint.InterpreterError t)
    • In the expression:
        Hint.runInterpreter
          $ do Hint.setImports ["Prelude"]
               Hint.interpret s (Hint.as :: t)
      In an equation for ‘eval’:
          eval s
            = Hint.runInterpreter
                $ do Hint.setImports ["Prelude"]
                     Hint.interpret s (Hint.as :: t)
    • Relevant bindings include
        eval :: String -> IO t (bound at app/Main.hs:26:1)
   |
26 | eval s = Hint.runInterpreter $ do
   |          ^^^^^^^^^^^^^^^^^^^^^^^^...

```

**Comment by yaitskov** [comment]
I would recommend to start with [this article](https://kseo.github.io/posts/2017-01-19-fun-with-hint.html).
Nonetheless it is 5 years old.

**Comment by gelisam** [comment]
Hmm, I vaguely remember defining a local `runInterpreter` which calls `Hint.runInterpreter` and throws errors as exceptions instead of `Left`s, so the examples can focus on the results. That explains both issues, but not why that local `runInterpreter` didn't make the cut. I'll try to add a test which validates that the code in the README runs, to make sure it doesn't get out of sync if we ever make backward-incompatible changes.

**Comment by gelisam** [comment]
runs just fine with `stack-8.10.4.yaml`, but with `stack-9.0.1.yaml`, doctest doesn't build, and with `cabal new-build`, doctest doesn't find hint. Let's make this test separate from the unit tests.
