### ISSUE TITLE
Are "-clear-package-db" and "-no-user-package-db" flags working?

### ISSUE THREAD

**Issue by polymorphicengine** [haskell-hint/hint#135]
I'm trying to set a custom place for my package database, so what I did first, is to delete my package database under
C:/.../cabal/store/ghc-9.0.1/
and hint tells me that it can't find the package db under that path. So far so good. But then I tried setting the arguments
"-clear-package-db" and "-no-user-package-db" in `unsafeRunInterpreterWithArgsLibdir` and it still throws the same error,
that it can't find the package db under that specific path.

-hide-all-packages also seems to have no effect?

**Comment by gelisam** [comment]
Hi! Sorry I missed this issue, life has taken over these last few months.

I would expect these flags to work, since the `-package-db` flag works for adding new package-db paths. Perhaps you have an environment variable set to that path which the ghc library picks up?

In any case, hint itself does not (yet) handle the package-db paths nor the list of visible packages, we currently delegate that to the ghc library via the arguments to `unsafeRunInterpreterWithArgsLibdir`, so someone would need to go through the ghc codebase in order to figure out why that doesn't work, and I don't think I'll have the bandwidth to do that anytime soon. Good luck!

**Comment by polymorphicengine** [comment]
I can't really remember the details of my issue here, but I think it actually does work, 
if I remeber right I forgot to do a `ghc-pkg --recache`
