### ISSUE TITLE
module search paths with Hadrian

### ISSUE THREAD

**Issue by juhp** [haskell-hint/hint#163]
I am not sure if this is a peculiarity of Fedora ghc,
but I am wondering how hint decides the search paths for global packages compared to ghc.

In the past for ghc < 9.2 (before hadrian, ie before Fedora 38),
Fedora Haskell libraries lived in the same directory as ghc's core libraries.
But with the current packaging under hadrian, this is no longer true:
eg on my system:

- ghc core libs are in `/usr/lib64/ghc-9.2.6/lib/x86_64-linux-ghc-9.2.6/`
- other libraries live in `/usr/lib64/ghc-9.2.6/lib/`.

ghc, ghci, cabal, etc have no trouble with this but it seems hint doesn't find the libraries in `/usr/lib64/ghc-9.2.6/lib/`.
eg If I try to use `extra` with `import Data.List.Extra` it fails to load:

```
ERROR: Won't compile:
Could not find module ‘Data.List.Extra’
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

I think this worked fine in Fedora with ghc-9.0 and earlier (strictly speaking we kind of skipped over 9.0), but my guess is this is related to the transition from make to hadrian, and the associated path changes.
Well I am sure this should be fixable, just not sure where to start looking.

**Comment by gelisam** [comment]
hint doesn't do anything special to point the ghc library to particular package databases, so if the behaviour has changed, it must be because the ghc library's behaviour has changed.

Prior to hint-0.9.0.7, hint did not have documentation nor tests indicating where hint looks for package databases. Different people got different behaviours depending on how they install ghc, whether they are using `stack` or `cabal`, how they install the libraries hint is loading, how they compile the program which is using hint, and how they run that program. If it turns out that which version of ghc is installed also plays a role, oh well, I guess the situation is even more complex than I thought.

With hint-0.9.0.7, the behaviour is _still_ depending on all those factors, but the README and [hackage documentation](https://hackage.haskell.org/package/hint-0.9.0.7/docs/Language-Haskell-Interpreter.html#v:setImports) now tells users to use a ghc environment file or to specify a `-package-db` flag via [`unsafeRunInterpreterWithArgs`](https://hackage.haskell.org/package/hint/docs/Language-Haskell-Interpreter-Unsafe.html#v:unsafeRunInterpreterWithArgs). I thus think it is reasonable to close this ticket as Won't Fix, because you are using hint in a way which diverges from what the documentation now recommends.

That being said, I think it might make sense to extend the documentation with platform-specific information explaining what package databases users can expect to see depending on the above factors, even if might make the documentation very long, because that stuff is not very well documented otherwise.

Also, even though I don't consider this a bug, I am willing to help you debug why hint's behaviour has changed even after I close this ticket.

**Comment by gelisam** [comment]
In particular, since each ghc environment file is tied to a specific version of ghc, might it be possible that you have a ghc environment file for a pre-9.2 version of ghc in your working directory, but that you don't have a ghc environment file for ghc-9.2? Or vice-versa. They look like this:

```
$ ls .ghc.environment.*
.ghc.environment.x86_64-linux-8.10.7  .ghc.environment.x86_64-linux-9.2.4  .ghc.environment.x86_64-linux-9.6.1
.ghc.environment.x86_64-linux-8.8.4   .ghc.environment.x86_64-linux-9.4.2
```

**Comment by juhp** [comment]
Thank you that's very helpful... let me try to dig a little and see what I can find first.

(For comparison I just checked Tumbleweed's packaging and they actually put all their library packages in `/usr/lib64/ghc-9.4.5/lib/x86_64-linux-ghc-9.4.5/` so I assume they are not affected.)

**Comment by gelisam** [comment]
Ok, if there are no environment files then GHC is going to use the [algorithm specified here](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/packages.html#package-databases) to determine the default package databases stack. I would thus check if `GHC_PACKAGE_PATH` is set, and use `ghc -v` to check if the package databases stack is what you expect. Keep in mind that stack and cabal may set this environment variable if you run your program with `stack run`, but not if you build an executable with `stack install` and then run the resulting executable directly.

**Comment by juhp** [comment]
Sorry, I am feeling bad: silly me - your latest comment woke me up - have been installing my hwk tree locally with stack
which indeed breaks non-core libraries doh - apologies I had forgotten this: the Fedora hwk package works just fine.
So nothing to do with Hadrian, just the usual issue that one must use `stack exec` to get the correct libs, doh.
Sorry about the false alarm, it's been a while since I worked with hint... :disappointed:

**Comment by gelisam** [comment]
No worries; there are so many moving parts, it's easy to accidentally move one of those moving parts without realizing that it makes a difference!
