### ISSUE TITLE
`doLoad` should be exposed

### ISSUE THREAD

**Issue by TomMD** [haskell-hint/hint#6]
The `loadModules` call always resets the GHC API, thus removing from scope any imports and extensions.  This behavior is undesirable for some use cases, so it would be nice to expose a non-resetting version of `loadModules` which currently exists as in the unexported `doLoad` function used by `loadModules`.

**Comment by mvdan** [comment]
I've encountered the same problem myself, and have worked around it by keeping a list of modules around to pass it to `loadModules`.

I'm not the author of the original code, so I'm not sure why this was exposed in this way. Also, `loadModules` doesn't simply call `reset` and `doLoad fs` - it does a little more:

```haskell
loadModules :: MonadInterpreter m => [String] -> m ()
loadModules fs = do -- first, unload everything, and do some clean-up
                    reset
                    doLoad fs `catchIE` (\e  -> reset >> throwM e)
```

Perhaps we want to expose something like `loadModulesInc` or `addModules` that runs the second line, thus resulting in the exact same behaviour minus the `reset`. Then again, if you want to do everything incrementally, resetting on any exception might not be the best idea.

Thoughts, @jcpetruzza?

**Comment by jcpetruzza** [comment]
The intended design was to use this as @mvdan says: let your program keep track of the modules it needs and the imports it wants in scope and have it call `loadModules` with the full list and if it succeeds, have it set again the imports.

I understand this makes the interface less convenient, but it seemed to me that there would be too many subtleties if we tried to make hint more smart: e.g., what to do if there is an error loading the modules? should we try to set the imports anyway? what if an import fails? should we keep the rest? Each application has different needs so I thought this should be handled at the application level.

That said, I think it makes sense to make hint smarter wrt language extensions and other compiler settings, and they should probably be preserved between calls to `loadModules`.

Regarding the resetting-on-exception issue; I think it makes sense to reset on an error, otherwise the interpreter will end up in an undefined state (in the sense that we don't know which modules are loaded). The question seems to be, what should we do if we try to load-other-modules-incrementally and this operation fails. Ideally one would want to to have hint in the state prior to the call, but this is no longer possible in general since the previously loaded modules may have changed already. In my opinion, resetting is the sensible thing to do here.

**Comment by mvdan** [comment]
Sounds like the only sane option is to expose `doLoad` as a lower level version of `loadModules`, leaving it clear that it is much easier to shoot oneself in the foot with it. Would everyone be OK with this?

**Comment by TomMD** [comment]
@mvdan That sounds good, I'd use it immediately.

**Comment by mvdan** [comment]
There is no going back after exposing `doLoad`, so I'd be happier with @jcpetruzza's confirmation that it isn't a stupid idea :)

**Comment by jcpetruzza** [comment]
I don't see any harm from exposing a function other than you'll need to maintain it. In case of doubt, you can export an `Internal` module for which you don't provide guarantees (and don't count it for the PVP) and put it there.

The only point I wanted to bring is that I currently don't clearly see how one would go about using it, so I wouldn't recommend using it in general. E.g., if one tries to load module `A` that depends on several other modules, one of which fails to compile; what can one do other than resetting?

**Comment by mvdan** [comment]
> The only point I wanted to bring is that I currently don't clearly see how one would go about using it, so I wouldn't recommend using it in general. E.g., if one tries to load module A that depends on several other modules, one of which fails to compile; what can one do other than resetting?

I was thinking of exposing it in Unsafe, which should make its rough edges clear.

**Comment by mvdan** [comment]
Actually, thinking about this again I don't think we should expose `doLoad`. The reason behind exposing more low-level functions in the Unsafe pacakge is that they can do things that you cannot do otherwise. You can do more things, but it's also much easier for them to bite you.

With `doLoad` though, there isn't any added feature. Sure, you can avoid having to keep a list of modules which might make your program slightly simpler to write. But essentially it would be the same program. So I don't think this warrants exposing an internal, unsafe function.

**Comment by TomMD** [comment]
This is an unfortunate conclusion.  The advantage of being able to set language pragma and modules external to a loaded file makes hint more useful as a compiler for DSLs.   The user of the DSL doesn't need to know all of Haskell, including being ignorant of pragma and modules.  To support this user, hint provides a compilation routine including lexing, parsing, type checking, and clean error messages.  

Without this additional export from Hint I think I'm forced to create temporary files and append these strings.  Much more work will be needed to locate any user modules and keep them in the same relative paths.

**Comment by mvdan** [comment]
I don't think I follow. What does keeping a list of loaded modules have to do with temporary files and concatenation of strings?

**Comment by TomMD** [comment]
Ideally, users of my DSL can write code such as:

```
action =
   do a <- dslFunction1 "Input value"
        dslFunction2 a
```

But because `loadModules` always resets the environment I need to either:

1. Read the original file and pre-pend `{-# LANGUAGE OverloadedStrings #-}` and `import TheDSLModules` before writing out to a temp file.  Then we can `loadModules tmpFile`.  If this is my solution I now am interfering with advanced users who might have two modules, importing one from the other, because the tmp file is in a different location and I will not have copied the other modules into place.
2. Teach my users more Haskell and have them add pragma and import statements.  It starts to feel like `public static void main`.

**Comment by mvdan** [comment]
I think I got confused earlier - it's not the loaded modules that you have to keep around with `loadModules`, it's the files themselves on disk. Is this where your problem originates, @TomMD?

If so, then I do see the limitation and will re-open the issue.

**Comment by mvdan** [comment]
Ping @TomMD

**Comment by TomMD** [comment]
> I think I got confused earlier - it's not the loaded modules that you have to keep around with loadModules, it's the files themselves on disk. Is this where your problem originates, @TomMD?

I don't understand this question, but I'll try to answer.  I wish for a version of `loadModules` that keeps the already-in-scope modules in scope in the GHC interpretation.  The pattern I'm after is `setImports` followed by `loadModulesDirtyState`:

```
import Language.Haskell.Interpreter

main :: IO ()
main = do
  e <- runInterpreter $ do
      setImports ["Data.Map"]
      loadModules ["Bar"] -- XXX But not this 'loadModules', I need the 'dirtyState' version.
      func <- interpret "action" (undefined :: IO ())
      liftIO func
  print e
```

And in the Bar module we simply have something that requires `Map`, such as  `action = print (empty :: Map () ())`.

Any discussion about files on disk is just me talking through the only work-around I know of to not having `loadModulesDirtyState`.  That is, copy the `Bar` module and programatically add the `import Data.Map` statement along with any pragmas prior to interpretation with Hint.  The act of copying the file likely places it in a temp directory and messes up any import or user-defined modules.

**Comment by mvdan** [comment]
@TomMD apologies that this got dropped. Happy to review and merge a patch to expose this in `Language.Haskell.Interpreter.Internal`, like Daniel suggested above. We would likely need a better name than `doLoad`.

Once merged and released, if we're happy with it, we can consider moving it out of that internal module.

**Comment by TomMD** [comment]
No worries @mvdan.   I'll look into making a patch on an up coming weekend.

**Comment by Wizek** [comment]
Any update on this @TomMD? I might also need this function.

**Comment by TomMD** [comment]
@wizek No, it seems this fell off my radar some time ago and I don't currently have the bandwidth to pick it up.

**Comment by mvdan** [comment]
For what it's worth, I no longer maintain Hint (#47), but there are other maintainers now. If someone wants to actively work on this, just send a PR.

**Comment by gelisam** [comment]
The suggested solution doesn't work: even if I call `doLoad` instead of `loadModules`, I still get `Not in scope: type constructor or class "Map"`.

The reason is that it isn't the `reset` in `loadModules` which is preventing `Bar.hs` from seeing `Map`, it's Haskell's module semantics. When `Main.hs` imports `Foo` then `Bar`, the definitions of `Foo` aren't available in `Bar`, they are only available in the rest of `Main.hs`. `Foo` and `Bar` are, intentionally, completely independent from each other.

Hint is a wrapper around the ghc API, and `GHC.load` obeys Haskell's module semantics, so there is nothing hint can do about it.

That being said, in your use case, you don't want to change Haskell's module semantics, you want to load a file written in a DSL, convert it into a Haskell module (e.g. by implicitly adding some imports), and load that. As you've explained yourself, you can do that today by writing that module to disk and then loading it, but that's more inconvenient than it should be. So I have reopened #66, which should make it more convenient.
