### ISSUE TITLE
ghc 8.0.1 compatibility?

### ISSUE THREAD

**Issue by yaxu** [haskell-hint/hint#62]
Hi,
hint-0.8.0 isn't compiling under ghc 8.0.1, due to lack of `GHC.withCleanupSession` (see below). Is this expected? Unfortunately debian (in this case, raspbian) stretch is still on ghc 8.0.1.

```
pi@lcd:~/src/feedforward $ cabal install hint
Resolving dependencies...
Configuring hint-0.8.0...
Building hint-0.8.0...
Failed to install hint-0.8.0
Build log ( /home/pi/.cabal/logs/hint-0.8.0.log ):
cabal: Entering directory '/tmp/cabal-tmp-2331/hint-0.8.0'
Configuring hint-0.8.0...
Building hint-0.8.0...
Preprocessing library hint-0.8.0...
[ 1 of 19] Compiling Hint.Util        ( src/Hint/Util.hs, dist/build/Hint/Util.o )
[ 2 of 19] Compiling Hint.CompatPlatform ( src/Hint/CompatPlatform.hs, dist/build/Hint/CompatPlatform.o )
[ 3 of 19] Compiling Control.Monad.Ghc ( src/Control/Monad/Ghc.hs, dist/build/Control/Monad/Ghc.o )

src/Control/Monad/Ghc.hs:38:5: error:
    Not in scope: ‘GHC.withCleanupSession’
    Perhaps you meant ‘GHC.withTempSession’ (imported from GhcMonad)
    Neither ‘Exception’, ‘GhcMonad’, ‘DynFlags’, ‘GHC’ nor ‘MonadUtils’ exports ‘withCleanupSession’.
cabal: Leaving directory '/tmp/cabal-tmp-2331/hint-0.8.0'
cabal: Error: some packages failed to install:
hint-0.8.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by mvdan** [comment]
I just got reminded of the comment you left on a commit two days ago - apologies for forgetting about it. It's easy to lose track of those if they're not in issues :)

GHC 8.0 is definitely still supported, see the Cabal file. I'm surprised that it's broken, as CI runs the full build and test suite on it. It uses 8.0.2 and you're on 8.0.1, which I think is the problem: https://ghc.haskell.org/trac/ghc/ticket/12398

Is there a reason why Stretch never got updated to 8.0.2? That seems unfortunate.

I always assumed that GHC patch releases were exclusively bugfixes, and never adding new APIs. With that in mind, it seems like for each version like 8.0, we should run CI on both 8.0.latest and 8.0.1.

I'd also like to know @gelisam's opinion, since he added the code in question. We can definitely release a bugfix version of Hint with a fix for this, if it's possible. Until then, you can always pin the latest 0.7.x version, which also supported GHC 8.0.

**Comment by mvdan** [comment]
I just remembered that this piece of code was copied over from GHC 8.2, so it's likely possible to also (or instead) pull the copy from 8.0.1. @yaxu if you'd like to send a patch it would be most welcome, as I wouldn't have to go through the trouble of installing that GHC version :)

**Comment by yaxu** [comment]
Thanks @mvdan, I don't know why stretch is on 8.0.1.

A bit outside my comfort zone, but I'll have a crack at a patch!
It seems that 8.0.1 has `withCleanupSession`, but it isn't exposed until 8.0.2 - https://github.com/ghc/ghc/commit/aedb41292d042963ad281641f85c26e5c9ea4d4d

**Comment by mvdan** [comment]
Yes - I'll reply on the PR.

**Comment by gelisam** [comment]
>  always assumed that GHC patch releases were exclusively bugfixes, and never adding new APIs.

According to the [PVP rule 2, "non-breaking changes"](https://pvp.haskell.org/#version-numbers), new bindings may be introduced when bumping from `A.B.1` to `A.B.2`. By the way, while with semantic versioning the third component is the patch version, [with the PVP the third component is the minor version, and it is the fourth component (if any) which is the patch version](https://pvp.haskell.org/faq/#how-does-the-pvp-relate-to-semantic-versioning-semver).

**Comment by mvdan** [comment]
I've been giving this some more thought. Is there any reason why anyone would stay on `8.0.1` without jumping to `8.0.2` and later "minor" versions? Ignoring distributions being behind on releases, that is.

Since such an upgrade should be non-breaking, I think it's fine to expect all users to be on the latest "minor" version. Otherwise, our matrix of GHC versions to test against quickly doubles - today, it would become:

```
8.4.2
8.4.1
8.2.1
8.0.2
8.0.1
```

We'd also have to test with versions in between the oldest and latest "minor" versions, just in case other edge cases like this one show up.

I'm worried about the extra work for the humans maintaining this project, but also for how long the CI jobs will get. Our total (not real) time clocks in at 1h already, so I don't look forward to doubling that.

Perhaps each hint version should specifically support full versions, to further clarify this. For example, the upcoming hint would support 8.4.2, 8.2.1, and 8.0.2. Different "minor" versions may work, but they are not guaranteed to.

And, if anyone really needs it to work on an older minor release, they can use the same strategy as if they were on 7.8 or older - use an older version of Hint.

Thoughts?

**Comment by mvdan** [comment]
To clarify - the upcoming version would support `>=8.4.2, >=8.2.1, and >=8.0.2`. That is, `8.4.3` would be supported, but not `8.4.1` or `8.4.1`.

Perhaps another way to avoid the testing matrix nightmare is to exclusively test against `A.B.1`, assuming that breaking changes never ever happen. I'm not sure how well that would work.

**Comment by yaxu** [comment]
Unfortunately the current stable version of debian (stretch) and derivatives are still on 8.0.1. This includes raspbian, where natively compiling from source on a raspberry pi is not practical.

**Comment by mvdan** [comment]
8.6 is out, so the upcoming release will drop 8.0. There's little point in keeping this open, since it hasn't had activity in a while.
