### ISSUE TITLE
How to capture stdout of an interpreter?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-hint/hint#77]
If one is using [`runStmt`](https://www.stackage.org/haddock/lts-12.1/hint-0.8.0/Language-Haskell-Interpreter.html#v:runStmt) and the function/expression contains a bunch of `puStrLn` statements, how does one capture this output?

I tried using `silently` from https://www.stackage.org/haddock/lts-12.1/silently-1.2.5/System-IO-Silently.html#v:capture which seems to work, but it works only outside of the `runInterpreter` command, like this:

```
silently $ runInterpreter $ do
  liftIO $ putStrLn "some debugging info"
  runStmt someStatement
```
... and it ends up capturing the debugging info, as well. I am unable to do the following, due to the "type jigsaw":

```
runInterpreter $ do
  liftIO $ putStrLn "some debugging info"
  silently $ runStmt someStatement

```

**Comment by gelisam** [comment]
Do you need the "possibly binding new names" part of `runStmt`? If you only want to run an IO action described by a string, you can `interpret` it into an `IO ()`, and then run that while capturing stdout:

    import Language.Haskell.Interpreter
    import System.IO.Silently
    
    someStatement :: String
    someStatement = "putStrLn \"what I want to capture\""
    
    -- |
    -- >>> interpretAndCapture someStatement
    -- some debugging info
    -- Right "what I want to capture\n"
    interpretAndCapture :: String -> IO (Either InterpreterError String)
    interpretAndCapture stmt = runInterpreter $ do
      setImports ["Prelude"]
      liftIO $ putStrLn "some debugging info"
      ioAction <- interpret stmt (as :: IO ())
      liftIO $ capture_ ioAction

If you do need `runStmt` to bind new names, I would try to rewrite the code you are interpreting so that it runs `capture` inside the interpreter. This is a bit tricky because `runStmt` doesn't return a value, so you'll have to store the result somewhere as a side-effect, like this:

    import Language.Haskell.Interpreter
    import System.IO.Silently
    import Text.Printf
    
    someBindingStatement :: String
    someBindingStatement = "unit <- putStrLn \"what I want to capture\" >> pure 42"
    
    -- |
    -- >>> runStmtAndCapture someBindingStatement
    -- some debugging info
    -- Right ("what I want to capture\n",42)
    runStmtAndCapture :: String -> IO (Either InterpreterError (String, Integer))
    runStmtAndCapture stmt = runInterpreter $ do
      setImports ["Prelude", "Data.IORef", "System.IO.Silently"]
      liftIO $ putStrLn "some debugging info"
      runStmt "ref <- newIORef \"\""
      let (var:"<-":expr) = words stmt
          stmt' = printf "%s <- capture (%s) >>= \\(capturedOutput, r) -> \
                         \writeIORef ref capturedOutput >> \
                         \pure r"
                         var
                         (unwords expr)
      runStmt stmt'
      ioAction <- interpret "readIORef ref" (as :: IO String)
      capturedOutput <- liftIO ioAction
      r <- interpret var (as :: Integer)
      pure (capturedOutput, r)

> I am unable to do the following, due to the "type jigsaw"

Indeed, `silently` requires its body to have type `IO a`, so you can't pass it an `InterpreterT IO a` instead. This is a very common problem which has nothing to do with hint, and the usual solution is to use something like [MonadBaseControl](http://hackage.haskell.org/package/monad-control) or [UnliftIO](http://hackage.haskell.org/package/unliftio) to make the type of `capture` more general. Unfortunately, hint does not provide an instance for either of those two typeclasses, and since it does not expose the data constructor for `InterpreterT`, you can't write an instance yourself either. If this is a problem for you, please file a separate ticket.
