### ISSUE TITLE
what's the difference between interpret and runStmt?

### ISSUE THREAD

**Issue by clojurians-org** [haskell-hint/hint#87]
i use  "runStmt" to run code block, but it don't get the return result back.
so i switch to "interpret", and try some simple example, and it works.

so i wonder what's the difference between two.
it seems the runStmt run in only IO monad, and interpret is more flexsible version?

**Comment by gelisam** [comment]
> i use "runStmt" to run code block, but it don't get the return result back.

Did you expect to get anything back? `runStmt` returns a value of type `()`!

> it seems the runStmt run in only IO monad, and interpret is more flexsible version?

No, they both run in any `m` which has a `MonadInterpreter` instance. The difference is that `interpret` evaluates a (pure) expression and gives you back the resulting value, without causing any side-effects, while `runStmt` evaluates an IO expression and performs its side-effects, possibly including the side-effect of binding a new variable in the interpreter's environment.

The difference is especially clear if you evaluate an expression of type `IO ()`; with `runStmt`, the IO side-effects will occur, whereas with `interpret`, you'll get back a value of type `IO ()` whose effects you can then run at your leisure.

I think the documentation for those two functions is pretty clear; the text is a bit short, but the types and the example make it pretty clear. In fact, I had no idea what the difference between the two was until just now, when I looked up their documentation in order to answer your question.

Of course, since I am already familiar with the basics of the library, it might be that this documentation is clearer for me than it is for you. Is there an alternate wording which would have made the difference clearer?
